FROM python:3.7
ENV PYTHONUNBUFFERED 0
ENV TZ="/usr/share/zoneinfo/Asia/Seoul"
WORKDIR /app
COPY requirements.txt ./
RUN apt-get update && apt-get install -y nginx net-tools vim
RUN pip install --upgrade pip && pip install -r requirements.txt
