FROM python:3.7
ENV PYTHONUNBUFFERED 0
ENV TZ="/usr/share/zoneinfo/Asia/Seoul"
WORKDIR /app
COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . /app/
RUN rm -rf /app/snowflake/static && mkdir /app/snowflake/static
EXPOSE 8000