# Generated by Django 3.0.5 on 2020-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MAN', '남'), ('WOMAN', '여'), ('BOTH', '모두'), ('SECRET', '비공개'), ('NONE', 'none')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_gender',
            field=models.CharField(choices=[('MAN', '남'), ('WOMAN', '여'), ('BOTH', '모두'), ('SECRET', '비공개'), ('NONE', 'none')], default='NONE', max_length=20),
        ),
    ]
