# Generated by Django 3.0.5 on 2020-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200601_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.CharField(blank=True, choices=[('KAKAO', 'kakao'), ('NAVER', 'naver'), ('APPLE', 'apple'), ('NONE', 'none')], default='NONE', max_length=20, null=True),
        ),
    ]
