# Generated by Django 3.0.7 on 2020-07-09 11:37

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200601_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='제목없는아이콘', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.create_icon_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, default='FFFFFF', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.CharField(blank=True, choices=[('KAKAO', 'kakao'), ('NAVER', 'naver'), ('APPLE', 'apple'), ('NONE', 'none')], default='NONE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='accounts.Icon', verbose_name='icon'),
        ),
    ]
