# Generated by Django 3.0.7 on 2020-07-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200704_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(blank=True, default='제목없는아이콘', max_length=100, null=True),
        ),
    ]
