# Generated by Django 3.0.7 on 2020-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200709_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_position',
            field=models.CharField(choices=[('PURPLE', '보라두리'), ('SKY', '하늘이'), ('NONE', '선택안함')], default='NONE', max_length=20),
            preserve_default=False,
        ),
    ]
