# Generated by Django 3.0.7 on 2020-10-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_position',
            new_name='position',
        ),
    ]
