# Generated by Django 3.0.7 on 2020-10-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201003_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('PURPLE', '보라두리'), ('SKY', '하늘이'), ('NONE', '선택안함')], default='NONE', max_length=20),
        ),
    ]
