# Generated by Django 3.0.7 on 2020-10-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0003_auto_20200709_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'products'), ('model', 'product')), models.Q(('app_label', 'reviews'), ('model', 'review')), models.Q(('app_label', 'labs'), ('model', 'sutra')), models.Q(('app_label', 'labs'), ('model', 'sutracomment')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
