# Generated by Django 3.0.5 on 2020-05-17 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MAN', '남'), ('WOMAN', '여'), ('BOTH', '모두'), ('NONE', 'none')], default='NONE', max_length=10, verbose_name='성별')),
                ('partner_gender', models.CharField(choices=[('MAN', '남'), ('WOMAN', '여'), ('BOTH', '모두'), ('NONE', 'none')], default='NONE', max_length=10, verbose_name='상대방 성별')),
                ('content', models.TextField(verbose_name='내용')),
                ('total', models.FloatField(default=0, verbose_name='종합 별점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewGel',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.Review')),
                ('viscosity', models.FloatField(default=0, verbose_name='점성')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gel', to='products.Gel', verbose_name='젤')),
            ],
            bases=('reviews.review',),
        ),
        migrations.CreateModel(
            name='ReviewCondom',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.Review')),
                ('oily', models.FloatField(default=0, verbose_name='윤활제 별점')),
                ('thickness', models.FloatField(default=0, verbose_name='두께 별점')),
                ('durability', models.FloatField(default=0, verbose_name='내구성 별점')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condom', to='products.Condom', verbose_name='콘돔')),
            ],
            bases=('reviews.review',),
        ),
    ]
