# Generated by Django 3.0.5 on 2020-05-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200528_2125'),
        ('reviews', '0002_auto_20200530_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcondom',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewgel',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='products.Product', verbose_name='제품'),
            preserve_default=False,
        ),
    ]
