# Generated by Django 3.0.5 on 2020-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200530_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gender',
            field=models.CharField(choices=[('MAN', '남'), ('WOMAN', '여'), ('BOTH', '모두'), ('NONE', 'none')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='partner_gender',
            field=models.CharField(choices=[('MAN', '남'), ('WOMAN', '여'), ('BOTH', '모두'), ('NONE', 'none')], default='NONE', max_length=20),
        ),
    ]
