# Generated by Django 3.0.5 on 2020-06-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200601_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='gender',
            field=models.CharField(choices=[('MAN', '남'), ('WOMAN', '여'), ('NONE', 'none')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='partner_gender',
            field=models.CharField(choices=[('MAN', '남'), ('WOMAN', '여'), ('NONE', 'none')], default='NONE', max_length=20),
        ),
    ]
