# Generated by Django 3.0.5 on 2020-05-17 06:50

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag_txt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('button_src', models.URLField(max_length=2000)),
                ('button_txt', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.create_path)),
                ('design_type', models.CharField(default='DEFAULT', max_length=50)),
                ('category', models.CharField(choices=[('NONE', '지정안됨'), ('PROD', '제품'), ('LAB', '실험실'), ('COMMU', '상담소')], default='NONE', max_length=5)),
                ('col', models.IntegerField(default=-1)),
                ('status', models.CharField(choices=[('DEL', 'Deleted'), ('DRAFT', 'Draft'), ('PUB', 'Published')], default='DRAFT', max_length=5)),
            ],
        ),
    ]
