# Generated by Django 3.0.7 on 2020-10-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201003_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomecard',
            name='design_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_welcome_card', to='home.DesignType'),
        ),
    ]
