# Generated by Django 3.0.7 on 2020-10-03 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import labs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0002_welcomecard_design_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sutra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kor', models.CharField(blank=True, max_length=255, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=labs.models.create_thumbnail_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=labs.models.create_image_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('purple_recommends_count', models.IntegerField(default=0, help_text='보라두리의 추천수')),
                ('purple_unrecommends_count', models.IntegerField(default=0, help_text='보라두리의 비추천수')),
                ('sky_recommends_count', models.IntegerField(default=0, help_text='하늘이의 추천수')),
                ('sky_unrecommends_count', models.IntegerField(default=0, help_text='하늘이의 비추천수')),
                ('not_yet_count', models.IntegerField(default=0, help_text='안해봤어요 수')),
                ('likes_count', models.IntegerField(default=0, help_text='찜 수')),
            ],
        ),
        migrations.AlterField(
            model_name='welcomecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=labs.models.create_path),
        ),
        migrations.CreateModel(
            name='SutraComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_position', models.CharField(choices=[('PURPLE', '보라두리'), ('SKY', '하늘이'), ('NONE', '선택안함')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes_count', models.IntegerField(default=0, help_text='찜 수')),
                ('sutra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Sutra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('PURPLE', '보라두리'), ('SKY', '하늘이')], max_length=10)),
                ('recommend_type', models.CharField(choices=[('RECOMMEND', '추천'), ('UNRECOMMEND', '비추천'), ('NOTYET', '안해봄')], max_length=20)),
                ('sutra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Sutra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
