# Generated by Django 3.0.7 on 2020-10-03 11:24

from django.db import migrations, models
import labs.models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_auto_20201003_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=labs.models.create_path),
        ),
    ]
