# Generated by Django 3.0.7 on 2020-10-03 17:30

from django.conf import settings
from django.db import migrations, models
import labs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0006_auto_20201003_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=labs.models.create_path),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('user', 'sutra')},
        ),
    ]
