# Generated by Django 3.0.7 on 2020-10-12 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import labs.models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_auto_20201004_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sutra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sutra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='sutra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='labs.Sutra'),
        ),
        migrations.AlterField(
            model_name='welcomecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=labs.models.create_path),
        ),
    ]
