# Generated by Django 3.0.5 on 2020-05-17 06:50

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=products.models.create_thumbnail_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.create_image_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.FloatField(default=0)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('num_of_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('num_of_views', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag_txt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('button_src', models.URLField(max_length=2000)),
                ('button_txt', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.create_path)),
                ('design_type', models.CharField(default='DEFAULT', max_length=50)),
                ('category', models.CharField(choices=[('NONE', '지정안됨'), ('PROD', '제품'), ('LAB', '실험실'), ('COMMU', '상담소')], default='NONE', max_length=5)),
                ('col', models.IntegerField(default=-1)),
                ('status', models.CharField(choices=[('DEL', 'Deleted'), ('DRAFT', 'Draft'), ('PUB', 'Published')], default='DRAFT', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Condom',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('category', models.CharField(choices=[('NORMAL', '일반형'), ('SLIM', '슬림형'), ('CHOBAK', '초박형'), ('DOLCHUL', '돌출형'), ('GGOKJI', '꼭지형'), ('DELAY', '사전지연형')], default='NORMAL', max_length=20)),
                ('thickness', models.FloatField(default=0, verbose_name='두께')),
                ('length', models.FloatField(default=0, verbose_name='길이')),
                ('width', models.FloatField(default=0, verbose_name='폭')),
                ('avg_oily', models.FloatField(default=0, verbose_name='윤활제 평균')),
                ('avg_thickness', models.FloatField(default=0, verbose_name='두께 평균')),
                ('avg_durability', models.FloatField(default=0, verbose_name='내구성 평균')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Gel',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('avg_viscosity', models.FloatField(default=0, verbose_name='점성 평균')),
            ],
            bases=('products.product',),
        ),
    ]
