# Generated by Django 3.0.5 on 2020-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer',
            new_name='manufacturer_kor',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_kor',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_eng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
