# Generated by Django 3.0.7 on 2020-07-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200528_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_field',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
