# Generated by Django 3.0.7 on 2020-07-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_search_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
