# Generated by Django 3.0.5 on 2020-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_num_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomecard',
            name='test_field',
            field=models.CharField(default='hello', max_length=5),
        ),
    ]
