# Generated by Django 3.0.7 on 2020-10-03 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_welcomecard_design_type'),
        ('products', '0005_welcomecard_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomecard',
            name='design_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_welcome_card', to='home.DesignType'),
        ),
    ]
